# Generated by Django 6.0.3 on 2026-07-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'Email Verification'), ('password_change', 'Password Change')], default='email_verify', max_length=20),
        ),
    ]
