# Generated by Django 6.0.3 on 2026-07-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_emailverificationcode_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'Email Verification'), ('password_change', 'Password Change'), ('email_change', 'Email Change')], default='email_verify', max_length=20),
        ),
    ]
