# Generated by Django 6.0.3 on 2026-07-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_emailverificationcode_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickedmovie',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
