# Generated by Django 6.0.3 on 2026-07-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pickedmovie_is_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
    ]
